# Generated by Django 4.1.7 on 2023-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0003_taskitem_tasklist_delete_tasklists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="title",
            field=models.CharField(
                choices=[
                    (1, "General Tasks"),
                    (2, "Priority Tasks"),
                    (3, "Class Tasks"),
                    (4, "Misc. Tasks"),
                ],
                max_length=100,
            ),
        ),
    ]
