# Generated by Django 4.1.7 on 2023-03-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0004_alter_tasklist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="title",
            field=models.CharField(
                choices=[
                    ("General Tasks", "General Tasks"),
                    ("Priority Tasks", "Priority Tasks"),
                    ("Class Tasks", "Class Tasks"),
                    ("Misc. Tasks", "Misc. Tasks"),
                ],
                max_length=100,
            ),
        ),
    ]
