# Generated by Django 4.1.7 on 2023-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0005_alter_tasklist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskitem",
            name="task_list",
            field=models.CharField(
                choices=[
                    ("GT", "General Tasks"),
                    ("PT", "Priority Tasks"),
                    ("CT", "Class Tasks"),
                    ("MT", "Misc. Tasks"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="TaskList",),
    ]
