# Generated by Django 4.1.7 on 2023-04-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0006_alter_taskitem_task_list_delete_tasklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskitem",
            name="task_list",
            field=models.CharField(
                choices=[
                    ("General Tasks", "General Tasks"),
                    ("Priority Tasks", "Priority Tasks"),
                    ("Class Tasks", "Class Tasks"),
                    ("Misc. Tasks", "Misc. Tasks"),
                ],
                max_length=100,
            ),
        ),
    ]
