# Generated by Django 4.1.7 on 2023-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0007_alter_taskitem_task_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskitem",
            name="checked",
            field=models.BooleanField(default=False, verbose_name="Checked"),
        ),
    ]
