# Generated by Django 4.1.7 on 2023-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockycal", "0008_alter_taskitem_checked"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskitem", name="checked",),
        migrations.AddField(
            model_name="taskitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
