# Generated by Django 4.1.7 on 2023-04-21 01:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cockycal', '0009_remove_taskitem_checked_taskitem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[500, 500], upload_to='images/'),
        ),
    ]
