# Generated by Django 4.1.3 on 2023-03-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.TextField(default="no birthday"),
        ),
        migrations.AddField(
            model_name="profile", name="name", field=models.TextField(default="name"),
        ),
        migrations.AddField(
            model_name="profile",
            name="occupation",
            field=models.TextField(default="no job"),
        ),
        migrations.AddField(
            model_name="profile",
            name="phonenumber",
            field=models.TextField(default="no phone number"),
        ),
    ]
