# Generated by Django 4.1.3 on 2023-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_birthday_profile_name_profile_occupation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.CharField(default="no birthday", max_length=40),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(default="name", max_length=40),
        ),
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.CharField(default="no job", max_length=40),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phonenumber",
            field=models.CharField(default="no phone number", max_length=40),
        ),
    ]
