# Generated by Django 4.1.7 on 2023-04-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_upcoming_events_and_more"),
        ("users", "0003_alter_profile_birthday_alter_profile_name_and_more"),
    ]

    operations = []
