# Generated by Django 4.1.3 on 2023-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("location", models.TextField(default="University of South Carolina")),
                (
                    "filterTag",
                    models.TextField(
                        choices=[
                            ("UofSC Event", "UofSC Event"),
                            ("Columbia Event", "Columbia Event"),
                            ("Athletic Event", "Athletic Event"),
                            ("Club Event", "Club Event"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        default="None",
                    ),
                ),
            ],
        ),
    ]
