# Generated by Django 4.1.3 on 2023-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="personal_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="posting_User_email",
            field=models.TextField(default="Web Scraped"),
        ),
    ]
