# Generated by Django 4.1.3 on 2023-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0002_event_personal_event_event_posting_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.TextField(default="User Added Event"),
        ),
    ]
