# Generated by Django 4.1.7 on 2023-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
