# Generated by Django 4.1.3 on 2023-04-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0003_event_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="url", new_name="description",
        ),
    ]
