# Generated by Django 4.1.3 on 2023-04-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0004_event_hide"),
        ("cal", "0004_rename_url_event_description"),
    ]

    operations = []
